project:
  type: book
  output-dir: docs

book:
  title: "Data Analysis in Natural Sciences: An R-Based Approach"
  subtitle: "From Field to Figures: Essential Methods for Environmental and Life Sciences"
  author: "Dr. Jimmy Moses (PhD)"
  date: "2025-03-27"
  cover-image: "images/dans_coverpage_final.png"
  site-url: https://jm0535.github.io/data-analysis-book/
  repo-url: https://github.com/jm0535/data-analysis-book
  chapters:
    - index.qmd
    - preface.qmd
    - part: "Getting Started"
      chapters:
        - chapters/01-introduction.qmd
        - chapters/02-data-basics.qmd
    - part: "Data Analysis Fundamentals"
      chapters:
        - chapters/03-exploratory-analysis.qmd
        - chapters/04-hypothesis-testing.qmd
        - chapters/05-statistical-tests.qmd
    - part: "Data Visualization"
      chapters:
        - chapters/06-visualization.qmd
        - chapters/07-advanced-visualization.qmd
    - part: "Advanced Topics"
      chapters:
        - chapters/08-regression.qmd  # Rendering issues fixed with distributed professional tips
        - chapters/09-conservation.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
    toc: true
    fig-width: 8
    fig-height: 6
    fig-dpi: 300
    fig-format: "png"
    fig-cap-location: bottom
    tbl-cap-location: top
    css: styles.css
    prefer-html: true
    crossref:
      fig-title: "Figure"
      tbl-title: "Table"
    footer-text: "DRAFT - Edition 1 - This book is currently in development. Content may change before final publication."
  pdf:
    documentclass: scrreprt
    prefer-html: true
    knitr:
      opts_chunk:
        dev: "png"

bibliography: references.bib
csl: apa.csl

execute:
  echo: true
  warning: false
  message: false
  eval: true
  always_allow_html: true
  prefer-html: true
  knitr:
    opts_chunk:
      dev: "png"
      screenshot.force: true
