project:
  type: book
  output-dir: _book

book:
  title: "Data Analysis in Natural Sciences: An R-Based Approach"
  subtitle: "From Field to Figures: Essential Methods for Environmental and Life Sciences"
  author: "Dr. Jimmy Moses (PhD)"
  date: "2025-03-27"
  cover-image: "docs/images/sapsucking.jpg"
  chapters:
    - index.qmd
    - preface.qmd
    - part: "Getting Started"
      chapters:
        - chapters/01-introduction.qmd
        - chapters/02-data-basics.qmd
    - part: "Data Analysis Fundamentals"
      chapters:
        - chapters/03-exploratory-analysis.qmd
        - chapters/04-hypothesis-testing.qmd
        - chapters/05-statistical-tests.qmd
    - part: "Data Visualization"
      chapters:
        - chapters/06-visualization.qmd
        - chapters/07-advanced-visualization.qmd
    - part: "Advanced Topics"
      chapters:
        - chapters/08-regression.qmd
        - chapters/09-conservation.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
    toc: true
    fig-width: 8
    fig-height: 6
    fig-dpi: 300
    fig-format: "png"
    fig-cap-location: bottom
    tbl-cap-location: top
    crossref:
      fig-title: "Figure"
      tbl-title: "Table"
    
  pdf:
    documentclass: book
    fig-width: 6.5
    fig-height: 4.5
    fig-dpi: 300
    fig-pos: "H"
    fig-cap-location: bottom
    tbl-cap-location: top
    colorlinks: true
    geometry:
      - margin=1in
    
bibliography: docs/references.bib
csl: docs/apa.csl

execute:
  echo: true
  warning: false
  message: false
  eval: true
  always_allow_html: true
